import '../justfile'


generate-large-random-files:
    mkdir -p notes
    head -c 100M </dev/urandom >notes/a.txt
    head -c 100M </dev/urandom >notes/b.txt
    head -c 100M </dev/urandom >notes/c.txt
    head -c 100M </dev/urandom >notes/d.txt

debug: 
    cargo build

    -rm -rf notes
    mkdir -p notes
    cd notes && cargo run -- init

    just generate-large-random-files

    cd notes && cat a.txt b.txt d.txt > file

    cd notes && cargo run -- stage file
    cd notes && cargo run -- commit -m "initial commit"

    cd notes && cat a.txt b.txt c.txt d.txt > file

    cd notes && DUH_VERBOSE=1 rust-gdb --args ../target/debug/duh stage file
